### ISSUE TITLE
Error in ancho_test

### ISSUE THREAD

**Issue by rdl58** [riccotti/LORE#10]
explainer = anchor_tabular.AnchorTabularExplainer(possible_outcomes, 
                                                  feature_names, X2E, 
                                                  categorical_names)
Traceback (most recent call last):

  File "<ipython-input-25-49ba35cd4f10>", line 3, in <module>
    categorical_names)

  File "anchor_tabular.py", line 45, in __init__
    n_values=n_values)

  File "validation.py", line 63, in inner_f
    return f(*args, **kwargs)

TypeError: __init__() got an unexpected keyword argument 'categorical_features'

Please help

**Comment by renatodeleone** [comment]
I suspect that the problem is with OneHotEncoder https://stackoverflow.com/questions/59476165/typeerror-init-got-an-unexpected-keyword-argument-categorical-features

"Since the latest build of sklearn library removed categorical_features parameter for onehotencoder class. It is advised to use ColumnTransformer class for categorical datasets. Refer the sklearn's official documentation for futher clarifications."

Any help will be appreciatedColumnTransformer class for categorical datasets. Refer the sklearn's official documentation for futher clarifications.
